spring:
  datasource:
    url: jdbc:mysql://localhost:3306/system?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456


  redis:
    port: 6379
    host: 127.0.0.1
    password:
    #redis数据库默认索引为0
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    #超时时间（单位毫秒）
    timeout: 10000

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8083
  servlet:
    context-path: /

